// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXvDtDOthxqLd24N6fyDZeyZoTjZN6Dts',
    appId: '1:449866735473:web:f539350e6f67c50039e0d0',
    messagingSenderId: '449866735473',
    projectId: 'crowdj',
    authDomain: 'crowdj.firebaseapp.com',
    storageBucket: 'crowdj.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5a_42esUEDK3vl-qahlUBpMMkb1q2Zo',
    appId: '1:449866735473:android:7f5f12a8e194045139e0d0',
    messagingSenderId: '449866735473',
    projectId: 'crowdj',
    storageBucket: 'crowdj.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ijMG2b-bzt8qs55dG1aTzHXdkCXl8-g',
    appId: '1:449866735473:ios:5aa0448d84a8139039e0d0',
    messagingSenderId: '449866735473',
    projectId: 'crowdj',
    storageBucket: 'crowdj.appspot.com',
    iosBundleId: 'it.polimi.dima.crowdj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6ijMG2b-bzt8qs55dG1aTzHXdkCXl8-g',
    appId: '1:449866735473:ios:30aba9a1482f80d439e0d0',
    messagingSenderId: '449866735473',
    projectId: 'crowdj',
    storageBucket: 'crowdj.appspot.com',
    iosBundleId: 'it.polimi.dima.crowdj.RunnerTests',
  );
}
