name: crowdj
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.6
  firebase_auth: ^4.15.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.1
  image_picker: ^1.0.5
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  http: ^1.1.2
  geoflutterfire2: ^2.3.15
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.2
  location: ^5.0.3
  envied: ^0.5.2
  spotify: ^0.12.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  intl: any
  flutter_localizations:
    sdk: flutter
  date_field: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.5
  firebase_auth_mocks: ^0.13.0
  mock_exceptions: ^0.8.2
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  fake_cloud_firestore: ^2.4.4
  envied_generator: ^0.5.2

flutter:
  assets:
    - lib/assets/
    - lib/feature/theme/constants/theme3.json
  uses-material-design: true
